# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'compile.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        MainWindow.setMinimumSize(QtCore.QSize(800, 500))
        MainWindow.setMaximumSize(QtCore.QSize(800, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 800, 500))
        self.stackedWidget.setMinimumSize(QtCore.QSize(800, 500))
        self.stackedWidget.setMaximumSize(QtCore.QSize(800, 500))
        self.stackedWidget.setStyleSheet("background-color: rgb(121, 144, 193);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.login_pg = QtWidgets.QWidget()
        self.login_pg.setObjectName("login_pg")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.login_pg)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(190, 60, 431, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Welcome_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Welcome_title.setFont(font)
        self.Welcome_title.setAutoFillBackground(False)
        self.Welcome_title.setStyleSheet("color: rgb(255, 255, 255);")
        self.Welcome_title.setObjectName("Welcome_title")
        self.verticalLayout_3.addWidget(self.Welcome_title, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.user_lbl = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.user_lbl.setFont(font)
        self.user_lbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.user_lbl.setObjectName("user_lbl")
        self.horizontalLayout_3.addWidget(self.user_lbl, 0, QtCore.Qt.AlignBottom)
        self.user_box = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.user_box.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.user_box.setObjectName("user_box")
        self.horizontalLayout_3.addWidget(self.user_box, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pass_lbl = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pass_lbl.setFont(font)
        self.pass_lbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.pass_lbl.setObjectName("pass_lbl")
        self.horizontalLayout_4.addWidget(self.pass_lbl, 0, QtCore.Qt.AlignTop)
        self.pass_box = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.pass_box.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pass_box.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_box.setObjectName("pass_box")
        self.horizontalLayout_4.addWidget(self.pass_box, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.login_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.login_btn.setStyleSheet("background-color: rgba(213, 213, 213, 213);")
        self.login_btn.setCheckable(True)
        self.login_btn.setChecked(False)
        self.login_btn.setObjectName("login_btn")
        self.verticalLayout_3.addWidget(self.login_btn)
        self.stackedWidget.addWidget(self.login_pg)
        self.query_pg = QtWidgets.QWidget()
        self.query_pg.setObjectName("query_pg")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.query_pg)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 30, 741, 421))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.query_title = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.query_title.setFont(font)
        self.query_title.setAutoFillBackground(False)
        self.query_title.setStyleSheet("color: rgb(255, 255, 255);")
        self.query_title.setAlignment(QtCore.Qt.AlignCenter)
        self.query_title.setObjectName("query_title")
        self.verticalLayout_2.addWidget(self.query_title)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.keyword_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.keyword_btn.setStyleSheet("\n"
"background-color: rgb(213, 213, 213);")
        self.keyword_btn.setCheckable(True)
        self.keyword_btn.setChecked(False)
        self.keyword_btn.setObjectName("keyword_btn")
        self.gridLayout_2.addWidget(self.keyword_btn, 0, 2, 1, 1, QtCore.Qt.AlignTop)
        self.accnum_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.accnum_btn.setStyleSheet("\n"
"background-color: rgb(213, 213, 213);")
        self.accnum_btn.setCheckable(True)
        self.accnum_btn.setChecked(False)
        self.accnum_btn.setObjectName("accnum_btn")
        self.gridLayout_2.addWidget(self.accnum_btn, 0, 1, 1, 1, QtCore.Qt.AlignTop)
        self.mrn_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.mrn_btn.setStyleSheet("\n"
"background-color: rgb(213, 213, 213);")
        self.mrn_btn.setCheckable(True)
        self.mrn_btn.setChecked(False)
        self.mrn_btn.setObjectName("mrn_btn")
        self.gridLayout_2.addWidget(self.mrn_btn, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.stackedWidget.addWidget(self.query_pg)
        self.csvman_pg = QtWidgets.QWidget()
        self.csvman_pg.setObjectName("csvman_pg")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.csvman_pg)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(40, 40, 721, 411))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.csv_man_title = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.csv_man_title.setFont(font)
        self.csv_man_title.setAutoFillBackground(False)
        self.csv_man_title.setStyleSheet("color: rgb(255, 255, 255);")
        self.csv_man_title.setAlignment(QtCore.Qt.AlignCenter)
        self.csv_man_title.setObjectName("csv_man_title")
        self.verticalLayout_4.addWidget(self.csv_man_title)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.csv_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.csv_btn.setStyleSheet("background-color: rgba(213, 213, 213, 213);")
        self.csv_btn.setCheckable(True)
        self.csv_btn.setObjectName("csv_btn")
        self.gridLayout_3.addWidget(self.csv_btn, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.maninput_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.maninput_btn.setStyleSheet("background-color: rgba(213, 213, 213, 213);")
        self.maninput_btn.setCheckable(True)
        self.maninput_btn.setObjectName("maninput_btn")
        self.gridLayout_3.addWidget(self.maninput_btn, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.stackedWidget.addWidget(self.csvman_pg)
        self.mrn_pg = QtWidgets.QWidget()
        self.mrn_pg.setObjectName("mrn_pg")
        self.verticalFrame_4 = QtWidgets.QFrame(self.mrn_pg)
        self.verticalFrame_4.setGeometry(QtCore.QRect(30, 30, 741, 451))
        self.verticalFrame_4.setMinimumSize(QtCore.QSize(741, 451))
        self.verticalFrame_4.setMaximumSize(QtCore.QSize(741, 451))
        self.verticalFrame_4.setObjectName("verticalFrame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalFrame_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.mrn_label = QtWidgets.QLabel(self.verticalFrame_4)
        self.mrn_label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.mrn_label.setFont(font)
        self.mrn_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.mrn_label.setObjectName("mrn_label")
        self.verticalLayout_5.addWidget(self.mrn_label, 0, QtCore.Qt.AlignHCenter)
        self.mrn_lbl = QtWidgets.QLabel(self.verticalFrame_4)
        self.mrn_lbl.setMinimumSize(QtCore.QSize(800, 12))
        self.mrn_lbl.setMaximumSize(QtCore.QSize(800, 12))
        self.mrn_lbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.mrn_lbl.setObjectName("mrn_lbl")
        self.verticalLayout_5.addWidget(self.mrn_lbl)
        self.mrn_box = QtWidgets.QLineEdit(self.verticalFrame_4)
        self.mrn_box.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mrn_box.setObjectName("mrn_box")
        self.verticalLayout_5.addWidget(self.mrn_box)
        self.mrn_start_date_lbl = QtWidgets.QLabel(self.verticalFrame_4)
        self.mrn_start_date_lbl.setMaximumSize(QtCore.QSize(16777215, 12))
        self.mrn_start_date_lbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.mrn_start_date_lbl.setObjectName("mrn_start_date_lbl")
        self.verticalLayout_5.addWidget(self.mrn_start_date_lbl)
        self.mrn_start_date_box = QtWidgets.QLineEdit(self.verticalFrame_4)
        self.mrn_start_date_box.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mrn_start_date_box.setObjectName("mrn_start_date_box")
        self.verticalLayout_5.addWidget(self.mrn_start_date_box)
        self.mrn_end_date_lbl = QtWidgets.QLabel(self.verticalFrame_4)
        self.mrn_end_date_lbl.setMaximumSize(QtCore.QSize(16777215, 12))
        self.mrn_end_date_lbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.mrn_end_date_lbl.setObjectName("mrn_end_date_lbl")
        self.verticalLayout_5.addWidget(self.mrn_end_date_lbl)
        self.mrn_end_date_box = QtWidgets.QLineEdit(self.verticalFrame_4)
        self.mrn_end_date_box.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mrn_end_date_box.setObjectName("mrn_end_date_box")
        self.verticalLayout_5.addWidget(self.mrn_end_date_box)
        self.mrn_modality_lbl = QtWidgets.QLabel(self.verticalFrame_4)
        self.mrn_modality_lbl.setMaximumSize(QtCore.QSize(16777215, 12))
        self.mrn_modality_lbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.mrn_modality_lbl.setObjectName("mrn_modality_lbl")
        self.verticalLayout_5.addWidget(self.mrn_modality_lbl)
        self.mrn_modality_box = QtWidgets.QLineEdit(self.verticalFrame_4)
        self.mrn_modality_box.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mrn_modality_box.setObjectName("mrn_modality_box")
        self.verticalLayout_5.addWidget(self.mrn_modality_box)
        self.mrn_keyword_lbl = QtWidgets.QLabel(self.verticalFrame_4)
        self.mrn_keyword_lbl.setMaximumSize(QtCore.QSize(16777215, 12))
        self.mrn_keyword_lbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.mrn_keyword_lbl.setObjectName("mrn_keyword_lbl")
        self.verticalLayout_5.addWidget(self.mrn_keyword_lbl)
        self.mrn_keyword_box = QtWidgets.QLineEdit(self.verticalFrame_4)
        self.mrn_keyword_box.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mrn_keyword_box.setObjectName("mrn_keyword_box")
        self.verticalLayout_5.addWidget(self.mrn_keyword_box)
        self.mrn_enter_btn = QtWidgets.QPushButton(self.verticalFrame_4)
        self.mrn_enter_btn.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.mrn_enter_btn.setCheckable(True)
        self.mrn_enter_btn.setObjectName("mrn_enter_btn")
        self.verticalLayout_5.addWidget(self.mrn_enter_btn)
        self.stackedWidget.addWidget(self.mrn_pg)
        self.acc_pg = QtWidgets.QWidget()
        self.acc_pg.setObjectName("acc_pg")
        self.verticalFrame_5 = QtWidgets.QFrame(self.acc_pg)
        self.verticalFrame_5.setGeometry(QtCore.QRect(30, 30, 741, 451))
        self.verticalFrame_5.setMinimumSize(QtCore.QSize(741, 451))
        self.verticalFrame_5.setMaximumSize(QtCore.QSize(741, 451))
        self.verticalFrame_5.setObjectName("verticalFrame_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalFrame_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.acc_label = QtWidgets.QLabel(self.verticalFrame_5)
        self.acc_label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.acc_label.setFont(font)
        self.acc_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.acc_label.setObjectName("acc_label")
        self.verticalLayout_9.addWidget(self.acc_label, 0, QtCore.Qt.AlignHCenter)
        self.acc_lbl = QtWidgets.QLabel(self.verticalFrame_5)
        self.acc_lbl.setMinimumSize(QtCore.QSize(800, 12))
        self.acc_lbl.setMaximumSize(QtCore.QSize(800, 12))
        self.acc_lbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.acc_lbl.setObjectName("acc_lbl")
        self.verticalLayout_9.addWidget(self.acc_lbl)
        self.acc_box = QtWidgets.QLineEdit(self.verticalFrame_5)
        self.acc_box.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.acc_box.setObjectName("acc_box")
        self.verticalLayout_9.addWidget(self.acc_box)
        self.acc_start_date_lbl = QtWidgets.QLabel(self.verticalFrame_5)
        self.acc_start_date_lbl.setMaximumSize(QtCore.QSize(16777215, 12))
        self.acc_start_date_lbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.acc_start_date_lbl.setObjectName("acc_start_date_lbl")
        self.verticalLayout_9.addWidget(self.acc_start_date_lbl)
        self.acc_start_date_box = QtWidgets.QLineEdit(self.verticalFrame_5)
        self.acc_start_date_box.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.acc_start_date_box.setObjectName("acc_start_date_box")
        self.verticalLayout_9.addWidget(self.acc_start_date_box)
        self.acc_end_date_lbl = QtWidgets.QLabel(self.verticalFrame_5)
        self.acc_end_date_lbl.setMaximumSize(QtCore.QSize(16777215, 12))
        self.acc_end_date_lbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.acc_end_date_lbl.setObjectName("acc_end_date_lbl")
        self.verticalLayout_9.addWidget(self.acc_end_date_lbl)
        self.acc_end_date_box = QtWidgets.QLineEdit(self.verticalFrame_5)
        self.acc_end_date_box.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.acc_end_date_box.setObjectName("acc_end_date_box")
        self.verticalLayout_9.addWidget(self.acc_end_date_box)
        self.acc_modality_lbl = QtWidgets.QLabel(self.verticalFrame_5)
        self.acc_modality_lbl.setMaximumSize(QtCore.QSize(16777215, 12))
        self.acc_modality_lbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.acc_modality_lbl.setObjectName("acc_modality_lbl")
        self.verticalLayout_9.addWidget(self.acc_modality_lbl)
        self.acc_modality_box = QtWidgets.QLineEdit(self.verticalFrame_5)
        self.acc_modality_box.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.acc_modality_box.setObjectName("acc_modality_box")
        self.verticalLayout_9.addWidget(self.acc_modality_box)
        self.acc_keyword_lbl = QtWidgets.QLabel(self.verticalFrame_5)
        self.acc_keyword_lbl.setMaximumSize(QtCore.QSize(16777215, 12))
        self.acc_keyword_lbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.acc_keyword_lbl.setObjectName("acc_keyword_lbl")
        self.verticalLayout_9.addWidget(self.acc_keyword_lbl)
        self.acc_keyword_box = QtWidgets.QLineEdit(self.verticalFrame_5)
        self.acc_keyword_box.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.acc_keyword_box.setObjectName("acc_keyword_box")
        self.verticalLayout_9.addWidget(self.acc_keyword_box)
        self.acc_enter_btn = QtWidgets.QPushButton(self.verticalFrame_5)
        self.acc_enter_btn.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.acc_enter_btn.setCheckable(True)
        self.acc_enter_btn.setObjectName("acc_enter_btn")
        self.verticalLayout_9.addWidget(self.acc_enter_btn)
        self.stackedWidget.addWidget(self.acc_pg)
        self.key_pg = QtWidgets.QWidget()
        self.key_pg.setObjectName("key_pg")
        self.verticalFrame_6 = QtWidgets.QFrame(self.key_pg)
        self.verticalFrame_6.setGeometry(QtCore.QRect(30, 30, 741, 451))
        self.verticalFrame_6.setMinimumSize(QtCore.QSize(741, 451))
        self.verticalFrame_6.setMaximumSize(QtCore.QSize(741, 451))
        self.verticalFrame_6.setObjectName("verticalFrame_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalFrame_6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.key_label = QtWidgets.QLabel(self.verticalFrame_6)
        self.key_label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.key_label.setFont(font)
        self.key_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.key_label.setObjectName("key_label")
        self.verticalLayout_10.addWidget(self.key_label, 0, QtCore.Qt.AlignHCenter)
        self.key_mrn_lbl = QtWidgets.QLabel(self.verticalFrame_6)
        self.key_mrn_lbl.setMinimumSize(QtCore.QSize(800, 12))
        self.key_mrn_lbl.setMaximumSize(QtCore.QSize(800, 12))
        self.key_mrn_lbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.key_mrn_lbl.setObjectName("key_mrn_lbl")
        self.verticalLayout_10.addWidget(self.key_mrn_lbl)
        self.key_mrn_box = QtWidgets.QLineEdit(self.verticalFrame_6)
        self.key_mrn_box.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.key_mrn_box.setObjectName("key_mrn_box")
        self.verticalLayout_10.addWidget(self.key_mrn_box)
        self.key_start_date_lbl = QtWidgets.QLabel(self.verticalFrame_6)
        self.key_start_date_lbl.setMaximumSize(QtCore.QSize(16777215, 12))
        self.key_start_date_lbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.key_start_date_lbl.setObjectName("key_start_date_lbl")
        self.verticalLayout_10.addWidget(self.key_start_date_lbl)
        self.key_start_date_box = QtWidgets.QLineEdit(self.verticalFrame_6)
        self.key_start_date_box.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.key_start_date_box.setObjectName("key_start_date_box")
        self.verticalLayout_10.addWidget(self.key_start_date_box)
        self.key_end_date_lbl = QtWidgets.QLabel(self.verticalFrame_6)
        self.key_end_date_lbl.setMaximumSize(QtCore.QSize(16777215, 12))
        self.key_end_date_lbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.key_end_date_lbl.setObjectName("key_end_date_lbl")
        self.verticalLayout_10.addWidget(self.key_end_date_lbl)
        self.key_end_date_box = QtWidgets.QLineEdit(self.verticalFrame_6)
        self.key_end_date_box.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.key_end_date_box.setObjectName("key_end_date_box")
        self.verticalLayout_10.addWidget(self.key_end_date_box)
        self.key_modality_lbl = QtWidgets.QLabel(self.verticalFrame_6)
        self.key_modality_lbl.setMaximumSize(QtCore.QSize(16777215, 12))
        self.key_modality_lbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.key_modality_lbl.setObjectName("key_modality_lbl")
        self.verticalLayout_10.addWidget(self.key_modality_lbl)
        self.key_modality_box = QtWidgets.QLineEdit(self.verticalFrame_6)
        self.key_modality_box.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.key_modality_box.setObjectName("key_modality_box")
        self.verticalLayout_10.addWidget(self.key_modality_box)
        self.key_keyword_lbl = QtWidgets.QLabel(self.verticalFrame_6)
        self.key_keyword_lbl.setMaximumSize(QtCore.QSize(16777215, 12))
        self.key_keyword_lbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.key_keyword_lbl.setObjectName("key_keyword_lbl")
        self.verticalLayout_10.addWidget(self.key_keyword_lbl)
        self.key_keyword_box = QtWidgets.QLineEdit(self.verticalFrame_6)
        self.key_keyword_box.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.key_keyword_box.setObjectName("key_keyword_box")
        self.verticalLayout_10.addWidget(self.key_keyword_box)
        self.key_enter_btn = QtWidgets.QPushButton(self.verticalFrame_6)
        self.key_enter_btn.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.key_enter_btn.setCheckable(True)
        self.key_enter_btn.setObjectName("key_enter_btn")
        self.verticalLayout_10.addWidget(self.key_enter_btn)
        self.stackedWidget.addWidget(self.key_pg)
        self.save_pg = QtWidgets.QWidget()
        self.save_pg.setObjectName("save_pg")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.save_pg)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(90, 80, 641, 291))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.save_title = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.save_title.setFont(font)
        self.save_title.setAutoFillBackground(False)
        self.save_title.setStyleSheet("color: rgb(255, 255, 255);")
        self.save_title.setAlignment(QtCore.Qt.AlignCenter)
        self.save_title.setObjectName("save_title")
        self.verticalLayout_6.addWidget(self.save_title)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.png_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.png_btn.setStyleSheet("\n"
"background-color: rgb(213, 213, 213);")
        self.png_btn.setCheckable(True)
        self.png_btn.setObjectName("png_btn")
        self.gridLayout.addWidget(self.png_btn, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.dicom_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.dicom_btn.setStyleSheet("\n"
"background-color: rgb(213, 213, 213);")
        self.dicom_btn.setCheckable(True)
        self.dicom_btn.setObjectName("dicom_btn")
        self.gridLayout.addWidget(self.dicom_btn, 0, 2, 1, 1, QtCore.Qt.AlignTop)
        self.video_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.video_btn.setStyleSheet("\n"
"background-color: rgb(213, 213, 213);")
        self.video_btn.setCheckable(True)
        self.video_btn.setObjectName("video_btn")
        self.gridLayout.addWidget(self.video_btn, 0, 3, 1, 1, QtCore.Qt.AlignTop)
        self.jpg_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.jpg_btn.setStyleSheet("\n"
"background-color: rgb(213, 213, 213);\n"
"")
        self.jpg_btn.setCheckable(True)
        self.jpg_btn.setDefault(True)
        self.jpg_btn.setFlat(False)
        self.jpg_btn.setObjectName("jpg_btn")
        self.gridLayout.addWidget(self.jpg_btn, 0, 1, 1, 1, QtCore.Qt.AlignTop)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.stackedWidget.addWidget(self.save_pg)
        self.overwrite_pg = QtWidgets.QWidget()
        self.overwrite_pg.setObjectName("overwrite_pg")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.overwrite_pg)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(80, 70, 641, 311))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.overwrite_title = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.overwrite_title.setFont(font)
        self.overwrite_title.setAutoFillBackground(False)
        self.overwrite_title.setStyleSheet("color: rgb(255, 255, 255);")
        self.overwrite_title.setAlignment(QtCore.Qt.AlignCenter)
        self.overwrite_title.setObjectName("overwrite_title")
        self.verticalLayout_7.addWidget(self.overwrite_title)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.overwrite_yes_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.overwrite_yes_btn.setStyleSheet("\n"
"background-color: rgb(213, 213, 213);")
        self.overwrite_yes_btn.setCheckable(True)
        self.overwrite_yes_btn.setObjectName("overwrite_yes_btn")
        self.gridLayout_4.addWidget(self.overwrite_yes_btn, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.overwrite_no_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.overwrite_no_btn.setStyleSheet("\n"
"background-color: rgb(213, 213, 213);")
        self.overwrite_no_btn.setCheckable(True)
        self.overwrite_no_btn.setObjectName("overwrite_no_btn")
        self.gridLayout_4.addWidget(self.overwrite_no_btn, 0, 1, 1, 1, QtCore.Qt.AlignTop)
        self.verticalLayout_7.addLayout(self.gridLayout_4)
        self.stackedWidget.addWidget(self.overwrite_pg)
        self.study_pg = QtWidgets.QWidget()
        self.study_pg.setObjectName("study_pg")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.study_pg)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(20, 40, 761, 381))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.studies_title = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.studies_title.setStyleSheet("color: rgb(255, 255, 255);")
        self.studies_title.setObjectName("studies_title")
        self.verticalLayout_8.addWidget(self.studies_title)
        self.study_box = QtWidgets.QListWidget(self.verticalLayoutWidget_7)
        self.study_box.setMaximumSize(QtCore.QSize(16777215, 500))
        self.study_box.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.study_box.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.study_box.setObjectName("study_box")
        self.verticalLayout_8.addWidget(self.study_box, 0, QtCore.Qt.AlignVCenter)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.cancel_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.cancel_btn.setStyleSheet("\n"
"background-color: rgb(213, 213, 213);")
        self.cancel_btn.setCheckable(True)
        self.cancel_btn.setObjectName("cancel_btn")
        self.gridLayout_5.addWidget(self.cancel_btn, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.ok_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.ok_btn.setStyleSheet("\n"
"background-color: rgb(213, 213, 213);")
        self.ok_btn.setCheckable(True)
        self.ok_btn.setObjectName("ok_btn")
        self.gridLayout_5.addWidget(self.ok_btn, 0, 1, 1, 1, QtCore.Qt.AlignTop)
        self.verticalLayout_8.addLayout(self.gridLayout_5)
        self.stackedWidget.addWidget(self.study_pg)
        self.progress_pg = QtWidgets.QWidget()
        self.progress_pg.setObjectName("progress_pg")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.progress_pg)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(140, 80, 511, 151))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget_4)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_11.addWidget(self.progressBar)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_11.addWidget(self.label_4)
        self.view_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.view_btn.setStyleSheet("background-color: rgba(213, 213, 213, 213);")
        self.view_btn.setCheckable(True)
        self.view_btn.setObjectName("view_btn")
        self.verticalLayout_11.addWidget(self.view_btn)
        self.stackedWidget.addWidget(self.progress_pg)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Welcome_title.setText(_translate("MainWindow", "Enter credentials to access VNA"))
        self.user_lbl.setText(_translate("MainWindow", "Username:"))
        self.pass_lbl.setText(_translate("MainWindow", "Password: "))
        self.login_btn.setText(_translate("MainWindow", "Log In"))
        self.query_title.setText(_translate("MainWindow", "How do you want to query studies?"))
        self.keyword_btn.setText(_translate("MainWindow", "Keyword"))
        self.accnum_btn.setText(_translate("MainWindow", "Accession Number"))
        self.mrn_btn.setText(_translate("MainWindow", "Patient MRN"))
        self.csv_man_title.setText(_translate("MainWindow", "Would you like to use a CSV or a Manual Input?"))
        self.csv_btn.setText(_translate("MainWindow", "CSV"))
        self.maninput_btn.setText(_translate("MainWindow", "Manual Input"))
        self.mrn_label.setText(_translate("MainWindow", "Enter query parameters (Patient MRN is necessary)"))
        self.mrn_lbl.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Patient MRN\'s separated by commas or spaces</span></p></body></html>"))
        self.mrn_start_date_lbl.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Start Date (YYYYMMDD format)</span></p></body></html>"))
        self.mrn_end_date_lbl.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">End Date (YYYYMMDD format)</span></p></body></html>"))
        self.mrn_modality_lbl.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Modality to limit the search to (use the 2-letter code used in DICOM, i.e. MR, CR, etc.)</span></p></body></html>"))
        self.mrn_keyword_lbl.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Keywords for series to exclude if they appear in the description (e.g. sub, localizer, cor)</span></p></body></html>"))
        self.mrn_enter_btn.setText(_translate("MainWindow", "Enter"))
        self.acc_label.setText(_translate("MainWindow", "Enter query parameters (Accession number is necessary)"))
        self.acc_lbl.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Accession Number</span></p><p><br/></p></body></html>"))
        self.acc_start_date_lbl.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Start Date (YYYYMMDD format)</span></p></body></html>"))
        self.acc_end_date_lbl.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">End Date (YYYYMMDD format)</span></p></body></html>"))
        self.acc_modality_lbl.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Modality to limit the search to (use the 2-letter code used in DICOM, i.e. MR, CR, etc.)</span></p></body></html>"))
        self.acc_keyword_lbl.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Keywords for series to exclude if they appear in the description (e.g. sub, localizer, cor)</span></p></body></html>"))
        self.acc_enter_btn.setText(_translate("MainWindow", "Enter"))
        self.key_label.setText(_translate("MainWindow", "Enter query parameters (Keyword is necessary)"))
        self.key_mrn_lbl.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Study Keywords, separated by commas</span></p></body></html>"))
        self.key_start_date_lbl.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Start Date (YYYYMMDD format)</span></p></body></html>"))
        self.key_end_date_lbl.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">End Date (YYYYMMDD format)</span></p></body></html>"))
        self.key_modality_lbl.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Modality to limit the search to (use the 2-letter code used in DICOM, i.e. MR, CR, etc.)</span></p></body></html>"))
        self.key_keyword_lbl.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Keywords for series to exclude if they appear in the description (e.g. sub, localizer, cor)</span></p></body></html>"))
        self.key_enter_btn.setText(_translate("MainWindow", "Enter"))
        self.save_title.setText(_translate("MainWindow", "Save As:"))
        self.png_btn.setText(_translate("MainWindow", "PNG"))
        self.dicom_btn.setText(_translate("MainWindow", "DICOM"))
        self.video_btn.setText(_translate("MainWindow", "VIDEO"))
        self.jpg_btn.setText(_translate("MainWindow", "JPG"))
        self.overwrite_title.setText(_translate("MainWindow", "Overwrite any existing folders?"))
        self.overwrite_yes_btn.setText(_translate("MainWindow", "Yes"))
        self.overwrite_no_btn.setText(_translate("MainWindow", "No"))
        self.studies_title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">The following studies were found based on your query. Select which studies you want to download.</span></p></body></html>"))
        self.cancel_btn.setText(_translate("MainWindow", "Cancel"))
        self.ok_btn.setText(_translate("MainWindow", "OK"))
        self.label_4.setText(_translate("MainWindow", "Please wait while your studies download..."))
        self.view_btn.setText(_translate("MainWindow", "View Your Studies"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

